SELECT
    s1.STOCKID,
    s1.STOCKNAME,
    s1.SYMBOL,
    TOTAL(s1.NUMSHARES) AS NUMSHARES,
    TOTAL(s1.VALUE * IFNULL(CH.CURRVALUE, c1.BASECONVRATE)) AS VALUE,
    TOTAL(s1.NUMSHARES * (s1.CURRENTPRICE - s1.PURCHASEPRICE) * IFNULL(CH.CURRVALUE, c1.BASECONVRATE)) AS UnRealizedPL
FROM ACCOUNTLIST_V1 AS a1
INNER JOIN STOCK_V1 AS s1
    ON s1.HELDAT = a1.ACCOUNTID
INNER JOIN CURRENCYFORMATS_V1 AS c1
    ON c1.CURRENCYID = a1.CURRENCYID
LEFT JOIN CURRENCYHISTORY_V1 AS CH
    ON CH.CURRENCYID = c1.CURRENCYID
    AND CH.CURRDATE = (
        SELECT MAX(CRHST.CURRDATE)
        FROM CURRENCYHISTORY_V1 AS CRHST
        WHERE CRHST.CURRENCYID = c1.CURRENCYID
    )
WHERE
    a1.ACCOUNTTYPE = 'Investment'
    AND a1.STATUS = 'Open'
GROUP BY
    s1.SYMBOL
ORDER BY
    VALUE DESC;
