select 
    t.TRANSID
    ,TRANSDATE,ACCOUNTNAME,PAYEENAME
    ,t.NOTES
    , case t.TRANSCODE when 'Deposit' then TRANSAMOUNT else -TRANSAMOUNT end TRANSAMOUNT
    ,m.PFX_SYMBOL, m.SFX_SYMBOL, m.GROUP_SEPARATOR, m.DECIMAL_POINT
from CHECKINGACCOUNT_V1 as t
	join PAYEE_V1 as p on p.PAYEEID=t.PAYEEID
	join ACCOUNTLIST_V1 as a on a.ACCOUNTID=t.ACCOUNTID
        join CURRENCYFORMATS_V1 as m on m.CURRENCYID=a.CURRENCYID
where t.NOTES="";