WITH
b AS (
    SELECT ACCOUNTID, STATUS,
           (CASE WHEN TRANSCODE = 'Deposit'
                 THEN TRANSAMOUNT
                 ELSE -TRANSAMOUNT END) AS TRANSAMOUNT,
           TRANSDATE
    FROM CHECKINGACCOUNT_V1
    WHERE STATUS <> 'V'
      AND IFNULL(DELETEDTIME, '') = ''
      AND DATE(substr(TRANSDATE, 1, 10)) <= DATE('&single_date')
      AND TRANSCODE IN ('Deposit', 'Withdrawal')

    UNION ALL

    SELECT ACCOUNTID, STATUS,
           -TRANSAMOUNT AS TRANSAMOUNT,
           TRANSDATE
    FROM CHECKINGACCOUNT_V1
    WHERE STATUS <> 'V'
      AND IFNULL(DELETEDTIME, '') = ''
      AND DATE(substr(TRANSDATE, 1, 10)) <= DATE('&single_date')
      AND TRANSCODE = 'Transfer'

    UNION ALL

    SELECT TOACCOUNTID AS ACCOUNTID, STATUS,
           TOTRANSAMOUNT AS TRANSAMOUNT,
           TRANSDATE
    FROM CHECKINGACCOUNT_V1
    WHERE STATUS <> 'V'
      AND IFNULL(DELETEDTIME, '') = ''
      AND DATE(substr(TRANSDATE, 1, 10)) <= DATE('&single_date')
      AND TRANSCODE = 'Transfer'
),

c AS (
    SELECT CURRENCYID, PFX_SYMBOL, SFX_SYMBOL,
           CURRENCY_SYMBOL, DECIMAL_POINT,
           GROUP_SEPARATOR, SCALE
    FROM CURRENCYFORMATS_V1
),

r AS (
    SELECT cf.CURRENCYID,
           IFNULL(ch.CURRVALUE, 1) AS CURRVALUE
    FROM CURRENCYFORMATS_V1 cf
    LEFT JOIN CURRENCYHISTORY_V1 ch
      ON cf.CURRENCYID = ch.CURRENCYID
     AND ch.CURRDATE = (
           SELECT MAX(CURRDATE)
           FROM CURRENCYHISTORY_V1
           WHERE CURRENCYID = ch.CURRENCYID
             AND CURRDATE <= '&single_date'
         )
),

base AS (
    SELECT
        a.ACCOUNTID,
        a.ACCOUNTNAME,
        a.ACCOUNTTYPE,

        SUBSTR(LTRIM(a.ACCOUNTNAME, '.'), 1, 4) AS GRP,

        a.INITIALBAL + IFNULL(SUM(b.TRANSAMOUNT), 0) AS BALANCE,

        c.PFX_SYMBOL,
        c.SFX_SYMBOL,
        c.CURRENCY_SYMBOL,
        IFNULL(r.CURRVALUE, 1) AS CURRVALUE,
        c.SCALE,

        ROUND(
            (a.INITIALBAL + IFNULL(SUM(b.TRANSAMOUNT), 0)) * IFNULL(r.CURRVALUE, 1),
        2) AS BASE_SINGLE,

        '0' AS IS_SUBTOTAL
    FROM ACCOUNTLIST_V1 a
    LEFT JOIN b ON a.ACCOUNTID = b.ACCOUNTID
    LEFT JOIN c ON a.CURRENCYID = c.CURRENCYID
    LEFT JOIN r ON r.CURRENCYID = c.CURRENCYID
    WHERE a.STATUS = 'Open'
      AND a.ACCOUNTTYPE NOT IN ('Investment', 'Asset')
    GROUP BY a.ACCOUNTID, a.ACCOUNTNAME
),

sub AS (
    SELECT
        'Subtotal ' || GRP AS ACCOUNTNAME,
        '' AS ACCOUNTTYPE,
        GRP,
        SUM(BALANCE) AS BALANCE,
        '' AS PFX_SYMBOL,
        '' AS SFX_SYMBOL,
        '' AS CURRENCY_SYMBOL,
        1 AS CURRVALUE,
        2 AS SCALE,
        '1' AS IS_SUBTOTAL,
        SUM(BALANCE * CURRVALUE) AS BASE_SUM
    FROM base
    WHERE GRP <> ''
    GROUP BY GRP
)

SELECT
    ACCOUNTNAME,
    ACCOUNTTYPE,
    BALANCE,
    PFX_SYMBOL,
    SFX_SYMBOL,
    CURRENCY_SYMBOL,
    CURRVALUE,
    SCALE,
    GRP,
    IS_SUBTOTAL,
    BASE_SINGLE,
    NULL AS BASE_SUM
FROM base

UNION ALL

SELECT
    ACCOUNTNAME,
    ACCOUNTTYPE,
    BALANCE,
    PFX_SYMBOL,
    SFX_SYMBOL,
    CURRENCY_SYMBOL,
    CURRVALUE,
    SCALE,
    GRP,
    IS_SUBTOTAL,
    NULL AS BASE_SINGLE,
    BASE_SUM
FROM sub

ORDER BY GRP, IS_SUBTOTAL, ACCOUNTNAME;
